hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from .views import Lista, Nuevo, Editar, buscar_municipio,ListaPdf,Grafica, eliminar

app_name = 'pacientes'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
   # path('eliminar/<int:pk>', Eliminar.as_view(), name='eliminar'),
    path('busca-municipio/', buscar_municipio, name='buscar_municipio'),
    path('pdf/', ListaPdf.as_view(), name='pdf'),
    path('graficas/', Grafica.as_view(), name='pacientes_graficas'),
    path('eliminar/<int:pk>', eliminar, name='eliminar'),


]

pacientes/models.py
from django.db import models


class Estado(models.Model):
    nombre = models.CharField('Nombre del estado',max_length=120)
    def __str__(self):
        return self.nombre
    

class Municipio(models.Model):
    nombre = models.CharField('Nombre del municipio',max_length=120)
    estado = models.ForeignKey(Estado, verbose_name="Estado", on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre


class Paciente(models.Model):
    TIPO_SANGRE =  [
        ('A+', 'A positivo'),
        ('A-', 'A negativo'),
        ('O+', 'O positivo'),
    ]
    nombre = models.CharField(max_length=60)
    primerApellido = models.CharField('Apellido paterno',max_length=60)
    segundoApellido = models.CharField('Apellido materno', max_length=60, null=True, blank=True)
    numero_ss = models.CharField('Número de Seguro Social',max_length=20)
    fecha_nac = models.DateField('Fecha de nacimiento')
    tipo_sangre = models.CharField('Tipo de sangre', max_length=3, choices=TIPO_SANGRE)
    municipio = models.ForeignKey(Municipio, verbose_name='Municipio', on_delete=models.SET_NULL, null=True)
    estado = models.ForeignKey(Estado, verbose_name='Estado', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre + ' ' + self.primerApellido
    

pacientes/forms.py
from .models import Paciente
from django.forms import ModelForm, TextInput, Select, DateInput


class PacienteForm(ModelForm):

    class Meta:
        model = Paciente
        fields = ('nombre','primerApellido','segundoApellido',
            'numero_ss','fecha_nac','tipo_sangre','estado','municipio')

        widgets = {
                'nombre':TextInput(attrs={'class':'form-control'}),
                'primerApellido':TextInput(attrs={'class':'form-control'}),
                'segundoApellido':TextInput(attrs={'class':'form-control'}),
                'numero_ss':TextInput(attrs={'class':'form-control'}),
                'fecha_nac':DateInput(attrs={'class':'form-control'}),
                'tipo_sangre':Select(attrs={'class':'form-control'}),
                'estado':Select(attrs={'class':'form-control'}),
                'municipio':Select(attrs={'class':'form-control'}),
        }

pacientes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Paciente, Municipio, Estado
from .forms import PacienteForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django_weasyprint import WeasyTemplateResponseMixin
from django.conf import settings
from django.views.generic import TemplateView
from django.db.models import Count
from datetime import date
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin


class Lista(LoginRequiredMixin, ListView):
    paginate_by = 5
    model = Paciente

class VistaPdf(ListView):
    model = Paciente
    template_name = 'pacientes/paciente_pdf.html'

class ListaPdf(WeasyTemplateResponseMixin, VistaPdf):
    passpdf_stylesheets = [ settings.STATICFILES_DIRS[0] ]
    pdf_attachment = False
    pdf_filename = 'pacientes.pdf'


class Nuevo(CreateView):
    model = Paciente
    form_class = PacienteForm
    
    success_url = reverse_lazy('pacientes:lista')

class Editar(UpdateView):
    model = Paciente
    form_class = PacienteForm
    extra_context = {'editar':True}

    success_url = reverse_lazy('pacientes:lista')

#class Eliminar(DeleteView):
#    model = Paciente
#    success_url = reverse_lazy('pacientes:lista')

def eliminar(request, pk):
    id = int(pk)
    paciente = get_object_or_404(Paciente,id = id)
    paciente.delete()
    return redirect('pacientes:lista')

def buscar_municipio(request):
    id_estado = request.POST.get('id',None)
    if id_estado:
        municipios = Municipio.objects.filter(estado_id=id_estado)
        data = [{'id':mun.id,'nombre':mun.nombre} for mun in  municipios]
        return JsonResponse(data, safe=False)
    return JsonResponse({'error':'Parámetro inválido'}, safe=False)


class Grafica(TemplateView):
    template_name = 'pacientes/grafica.html'
    # pacientes_tipo = Paciente.objects.all().values('tipo_sangre').annotate(cuantos=Count('tipo_sangre'))
    # tipos = Paciente.objects.all()

    datos = []
    # tipos_de_sangre = []
    # cuantos=0
    # for tipo in tipos:
    #     if tipo.tipo_sangre in tipos_de_sangre:
    #         pass
    #     else:
    #         tipos_de_sangre.append(tipo.tipo_sangre)
    #         pt=pacientes_tipo[cuantos]
    #         num=pt['cuantos']
    #         datos.append({'name':tipo.tipo_sangre, 'data':[num]})
    #     cuantos=cuantos+1

    datos2 = []
    # hoy = date.today()
    # edades = Paciente.objects.all()
    # edades_existentes = []
    # ninos1=0
    # ninos2=0
    # ninos3=0
    # adoles=0
    # jovenes=0
    # adultos1=0
    # adultos2=0


    # for edad in edades:
    #     año_paciente=edad.fecha_nac
    #     fecha=hoy.year - año_paciente.year - ((hoy.month, hoy.day) < (año_paciente.month, año_paciente.day))
    #     if fecha <= 3:
    #         ninos1=ninos1+1
    #     if fecha>3 and fecha<=7:
    #         ninos2=ninos2+1
    #     if fecha>7 and fecha<=12:
    #         ninos3=ninos3+1
    #     if fecha>12 and fecha<=17:
    #         adoles=adoles+1
    #     if fecha>17 and fecha<=29:
    #         jovenes=jovenes+1
    #     if fecha>29 and fecha<=49:
    #         adultos1=adultos1+1
    #     if fecha>=50:
    #         adultos2=adultos2+1

    # datos2.append({'name':'niños 0-3 años', 'data':[ninos1]})
    # datos2.append({'name':'niños 4-7 años', 'data':[ninos2]})
    # datos2.append({'name':'niños 8-12 años', 'data':[ninos3]})
    # datos2.append({'name':'adolescentes 13-17 años', 'data':[adoles]})
    # datos2.append({'name':'jovenes 18-29 años', 'data':[jovenes]})
    # datos2.append({'name':'adultos 30-49 años', 'data':[adultos1]})
    # datos2.append({'name':'adultos 50 años o más', 'data':[adultos2]})
        


   

    extra_context = {'datos':datos,'datos2':datos2}

pacientes/templates/pacientes/grafica.html
{% extends 'base.html' %}

{% block titulo %}
    Gráficas
{% endblock titulo %}

{% block contenido %}
    <div id="grafica" style="min-width: 310px;height: 400px; margin: 0 auto;"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting-data.js"></script> 


    </script>
    <script>
        Highcharts.chart('grafica',{
            lang:{
                downloadCSV: 'Descarga CSV',
                downloadJPEG: 'Descarga imagen JPEG',
                downloadPDF: 'Descarga PDF',
                downloadPNG: 'Descarga imagen PNG',
                downloadSVG: 'Descarga en imagen de vectores',
                viewFullscreen: 'Ver en pantalla completa',
                printChart: 'Imprimir gráfica'
            },
            chart:{
                type: 'column'
            },
            title: {
                text: 'Gráfica de tipo de sangre'
            },
            subtitle: {
                text: 'Cuantos pacientes por tipo de sangre'
            },
            xAxis:{
                categories: ['Tipo']
            },
            yAxis:{
                min:0,
                title:{
                    text: 'Numero de pacientes'
                }
            },
            plotOptions:{
                column:{
                    pointPaddin: 0.2,
                    borderWidth: 0,

                }
            },
            series: {{datos|safe}}
            
        });
    </script>


</script>

<br>
<br>

<div id="grafica2" style="min-width: 310px;height: 400px; margin: 0 auto;"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting-data.js"></script> 
<script>
    Highcharts.chart('grafica2',{
        lang:{
            downloadCSV: 'Descarga CSV',
            downloadJPEG: 'Descarga imagen JPEG',
            downloadPDF: 'Descarga PDF',
            downloadPNG: 'Descarga imagen PNG',
            downloadSVG: 'Descarga en imagen de vectores',
            viewFullscreen: 'Ver en pantalla completa',
            printChart: 'Imprimir gráfica'
        },
        chart:{
            type: 'column'
        },
        title: {
            text: 'Gráfica de edad de pacientes'
        },
        subtitle: {
            text: 'Cuantos pacientes por edad'
        },
        xAxis:{
            categories: ['Edad']
        },
        yAxis:{
            min:0,
            title:{
                text: 'Numero de pacientes'
            }
        },
        plotOptions:{
            column:{
                pointPaddin: 0.2,
                borderWidth: 0,

            }
        },
        series: {{datos2|safe}}
        
    });
</script>
    
{% endblock contenido %}

pacientes/templates/pacientes/paciente_confirm_delete.html
{% extends 'base.html' %}
{% block titulo %}
    Eliminar paciente
{% endblock titulo %}

{% block contenido %}

<form method="post">
    {% csrf_token %}
    <p>Quieres eliminar el paciente "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Sí, si quiero">
    <a href="{% url 'pacientes:lista' %}" class="btn btn-secondary" >Mejor no</a>
</form>

{% endblock contenido %}

pacientes/templates/pacientes/paciente_form.html
{% extends 'base.html' %}

{% block titulo %}
    Agrega paciente
{% endblock titulo %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if editar %}
                        Modificar paciente
                    {% else %}
                        Nuevo paciente
                    {% endif %}
                </h3>
            </div>
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="{% if editar %}Guardar cambios{% else %}Agregar{% endif %}">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    

pacientes/templates/pacientes/paciente_list.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}

{% block contenido %}
<h1>Lista de pacientes</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
            <td>
                <a title="Actualiza paciente" class="btn btn-warning" href="{% url 'pacientes:editar' paciente.id %}">
                    <i class="far fa-edit"></i>
                </a>

                
                    <a class="btn btn-danger" href="javascript:eliminarPacienteModal( '{% url 'pacientes:eliminar' paciente.id %}' )">
                        <i class="far fa-trash-alt"> </i>
                    </a>
              

            </td>
        </tr>
        {% endfor %}

        <td>
            <div class="col-4">
                <a title="Grafica" class="btn btn-success"
                    href="{% url 'pacientes:pacientes_graficas' %}">Grafica</a>
            </div>
            <div class="col-4">
                <a title="Reporte" class="btn btn-success" href="{% url 'pacientes:pdf' %}">Generar PDF </a>
            </div>
        </td>
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">&laquo; First</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                aria-disabled="true">Previous</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="page-item">
            {% if num == 1 %}
            <a class="page-link" href="{{ profiles_1st_page_url }}">{{ num }}</a>
            {% else %}
            {% if num|add:"-3" <= page_obj.number and page_obj.number <= num|add:"3" %}
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            {% elif num|divisibleby:"10" or num == page_obj.paginator.num_pages %}
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endif %}
        </li>
        {% endif %}

        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1"
                aria-disabled="true">Next</a></li>
        <li class="page-item"><a class="page-link" ¨href="?page={{ page_obj.paginator.num_pages }}" tabindex="-1"
                aria-disabled="true">Last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>



<button hidden id="btnModal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Eliminar Paciente</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Vas a borrar al paciente, ¿Estas seguro?
        </div>
        <div class="modal-footer">
          <button type="button"  data-dismiss="modal"><a class="btn btn-default" href=""> Cancelar</a></button>
          <button type="button" ><a class="btn btn-primary" id="confirmaEliminacion" href=""> Eliminar</a></button>
        </div>
      </div>
    </div>
  </div>

  

<script>
    setTimeout(function(){
        if($('#msg').length > 0){
            $('#msg').remove()
        }
    },4000);

    function eliminarPacienteModal(url) {
        document.querySelector("#confirmaEliminacion").setAttribute('href',url);
        document.querySelector("#btnModal").click()
    }

</script>


{% endblock contenido %}

pacientes/templates/pacientes/paciente_pdf.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}
    
{% block contenido %}
<h1>Lista de pacientes</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td><div class="btn-primary"> {{paciente.id}} </div></td>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
           
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}
    